#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        child_frame_id: ground_truth/base_link
        parent_frame_id: ground_truth
        use_new_coordinates: true
    '2':
        child_frame_id: ground_truth/head_link
        parent_frame_id: ground_truth
        use_new_coordinates: true
optitrack_config:
        multicast_address: 224.0.0.3

poses_to_one_topic: true # If set true then poses are published on below topic.
poses_topic_name: mocap_bodies